<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11019" started-at="2023-01-21T17:40:48Z" finished-at="2023-01-21T17:40:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11019" started-at="2023-01-21T17:40:48Z" finished-at="2023-01-21T17:40:59Z">
      <class name="com.app.LoginTest.ValidateDataIsSorted">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="beforeSuite" is-config="true" duration-ms="45" started-at="2023-01-21T17:40:47Z" finished-at="2023-01-21T17:40:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="beforeTest" is-config="true" duration-ms="1" started-at="2023-01-21T17:40:48Z" finished-at="2023-01-21T17:40:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforClass()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="beforClass" is-config="true" duration-ms="4747" started-at="2023-01-21T17:40:48Z" finished-at="2023-01-21T17:40:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="PASS" signature="beforMethod()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="beforMethod" is-config="true" duration-ms="2319" started-at="2023-01-21T17:40:52Z" finished-at="2023-01-21T17:40:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforMethod -->
        <test-method status="FAIL" signature="amountData()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="amountData" duration-ms="2767" started-at="2023-01-21T17:40:55Z" finished-at="2023-01-21T17:40:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.app.LoginTest.ValidateDataIsSorted.amountData(ValidateDataIsSorted.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amountData -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="afterClass" is-config="true" duration-ms="901" started-at="2023-01-21T17:40:58Z" finished-at="2023-01-21T17:40:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethpd()[pri:0, instance:com.app.LoginTest.ValidateDataIsSorted@23aae55]" name="afterMethpd" is-config="true" duration-ms="0" started-at="2023-01-21T17:40:58Z" finished-at="2023-01-21T17:40:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethpd -->
      </class> <!-- com.app.LoginTest.ValidateDataIsSorted -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
